[build]
  base    = "." # 또는 이 라인을 삭제
  command = "npm run build" 
  publish = "client/dist" # publish 경로는 client/dist로 유지하거나 실제 빌드 결과물 위치로 변경

# SPA 리다이렉트 설정 (필요한 경우)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200