[build]
  base    = "client"
  command = "npm run build" # client/package.json의 빌드 스크립트에 따라 yarn build, pnpm build 등으로 변경
  publish = "dist"

# SPA 리다이렉트 설정 (필요한 경우)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200